### ISSUE TITLE
[Appeal]: Discord changed part of my code from `")` to `%22)` that ended up running for too long

### ISSUE THREAD

**Issue by KLanausse** [mfdlabs/grid-bot-support#11]
### You have read the blacklist guidelines?

- [X] I double checked the guidelines and my appeal conforms to them.

### You haven't been blacklisted before?

- [X] I double checked the blacklist and I haven't been blacklisted before.

### The ID of the Discord User you are appealing for. If you are appealing for a guild this must be the ID of the owner.

275033949695115264

### The date you were blacklisted.

2022-04-19 1:57 PM EST

### The ID of the guild you think you were blacklisted in or you are getting a blacklist revoked for.

960779064719851520

### The ID of the channel you think you were blacklisted in. This does not apply if you are appealing guild blacklist.

961033234760744990

### The reason you are appealing.

I'm appealing as I was blacklisted a few months ago for trying to run code that ended up being edited by Discord which ended up turning `game:Load("http://www.roblox.com/asset/?ID=1818")` into `game:Load("http://www.roblox.com/asset/?ID=1818%22)` which may ended up adding the rest of the code to the same string the URL was apart of that it ended up not liking

### An apology for the moderation team.

I would like to apologize for any problems this may have caused and I'll try to be more cautious when dealing with code that has URLs next time

### Images

![image](https://user-images.githubusercontent.com/66651363/192172363-0aedf1b4-92de-4730-9fa5-8839c22dd609.png)

**Comment by nikita-petko** [comment]
The problem here is not the escaped url, the executor parses that just fine. The problem here is the call to game:Load().

The base url of the executor is not www.roblox.com, and will therefore be transformed to a url that doesn't exist, essentially making it infinitely load as it keeps retrying the url over and over again, hence the timeout.

Avoid using things that may make HTTP calls.

**Comment by KLanausse** [comment]
Ah. I wasn't aware of that and will keep that in mind for next time.

Also I find it odd that dat did the exact same thing as he saw what happened to me.
![image](https://user-images.githubusercontent.com/66651363/193412171-0c5fa8f5-3b72-4b93-a712-394a786b5f52.jpeg)

Anyways thank you for the response.

**Comment by nikita-petko** [comment]
When the instance recovery comes into affect, this will tend to not be an issue anymore

**Comment by nikita-petko** [comment]
Anyway I've gone ahead and removed the blacklist, if you could get me the IDs of the other user there that said they were blacklisted that would be nice.
